### ISSUE TITLE
`there is no reactor running, must be called from the context of a Tokio 1.x runtime`

### ISSUE THREAD

**Issue by sassman** [EmbarkStudios/relnotes#2]
**Describe the bug**
I wanted to try out relnotes for [cargo-generate](https://github.com/cargo-generate/cargo-generate) but I'm getting this error message:

```sh
relnotes cargo-generate/cargo-generate@0.5.3
[2021-02-08T19:01:33Z INFO  relnotes] Using `0.5.3` as version number.
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/blocking/pool.rs:85:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
1. just run `relnotes cargo-generate/cargo-generate@0.5.3`
2. same happens when providing a config file
3. `'there is no reactor running, must be called from the context of a Tokio 1.x runtime'`

**Expected behavior**
It should work as described in the README.

**Device:**
 - MacOS 11.2 (amd64)

**Additional context**
```sh
cargo --version && rustc --version
cargo 1.49.0 (d00d64df9 2020-12-05)
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I haven't run into this, and I was just using it yesterday, but I'll investigate later today.

**Comment by sassman** [comment]
I've tried it on a different machine. Same issue. 
Do you run it on nightly maybe?

**Comment by XAMPPRocky** [comment]
@sassman Running on macOS 11.1 with the latest stable works for me.

```markdown
# cargo-generate 0.5.3 (2021-02-09)

- [release(v0.5.3): add date+version+changes to the changelog](https://github.com/cargo-generate/cargo-generate/pull/288)
- [chore(deps): bump serde from 1.0.119 to 1.0.123](https://github.com/cargo-generate/cargo-generate/pull/287)
- [chore(deps): bump liquid from 0.21.4 to 0.21.5](https://github.com/cargo-generate/cargo-generate/pull/286)
- [chore(deps): bump assert_cmd from 1.0.2 to 1.0.3](https://github.com/cargo-generate/cargo-generate/pull/285)
- [chore(deps): bump cargo from 0.50.0 to 0.50.1](https://github.com/cargo-generate/cargo-generate/pull/284)
- [chore(deps): bump liquid-lib from 0.21.1 to 0.21.2](https://github.com/cargo-generate/cargo-generate/pull/283)
- [chore(deps): bump liquid-derive from 0.21.0 to 0.21.1](https://github.com/cargo-generate/cargo-generate/pull/282)
- [chore(deps): bump liquid-core from 0.21.2 to 0.21.3](https://github.com/cargo-generate/cargo-generate/pull/281)

## Contributors

- [dependabot-preview[bot]](https://github.com/apps/dependabot-preview)
- [sassman](https://github.com/sassman)
```

**Comment by sassman** [comment]
Since it seems to be a `tokio` related issue, I have tried 2 things.

1. `cargo install --force relnotes --locked` that worked.
2. `rm -rf $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-* && cargo install --force relnotes` this did not work.

Could you please double check what tokio version you have?

I have `tokio-1.2.0` that fails. But `tokio v0.2.25` works.

**Comment by XAMPPRocky** [comment]
Okay, running `cargo update` I can reproduce this, I will update the dependencies and deploy a fix soon.

**Comment by sassman** [comment]
thanks a lot.

**Comment by XAMPPRocky** [comment]
Fixes published in `0.1.2`.

**Comment by sassman** [comment]
BTW, I want to recommend the [dependabot](https://dependabot.com/) that keeps dependencies updated and created PR for version bumps. It helped me a lot on a few projects.

**Comment by XAMPPRocky** [comment]
Thanks, I do use it on my personal projects. Though it wouldn't have helped here since there was code changes needed, and we don't have it enabled on Embark repos since updating dependencies generates a lot of noise with each dependency being its own PR with notification, which is a lot when you have hundreds of crates.

**Comment by ATmel91** [comment]
`thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', C:\Users\myusername\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\blocking\pool.rs:85:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

jesus christ. nothing fixes this now does it?

rolling back to 0.1.2 not only does not work, but also causes more issues. because i need to use `#[tokio::main]` and that doesn't work, along with other newer features. awesome.

EDIT: 0.2.25 does not seem to work either. fun.

**Comment by XAMPPRocky** [comment]
@ATmel91 relnotes `0.1.2` should now work, you need to have Tokio 1.0 for it to work.
